pub mod agent;
pub mod commands;
pub mod context;
pub mod error;
pub mod external;
pub mod file_util;
pub mod hooks;
pub mod message;
pub mod openrouter;
pub mod plan;
pub mod project;
pub mod prompt;
pub mod provider;
pub mod runtime;
pub mod session;
pub mod tool_spec;
pub mod tools;

pub use agent::Agent;
pub use commands::{CommandRegistry, CommandStep, CustomCommand};
pub use context::ExecutionContext;
pub use error::{Error, Result};
pub use external::{ExternalTool, ExternalToolRegistry};
pub use hooks::{HookRegistry, ToolHooks};
pub use message::{Content, Message, Role};
pub use openrouter::OpenRouterProvider;
pub use plan::{Plan, TodoItem, TodoStatus};
pub use project::load_project_instructions;
pub use provider::{Provider, ProviderResponse, ScriptedProvider};
pub use runtime::RuntimeOptions;
pub use session::Session;
pub use tool_spec::ToolSpec;
